import { generatePath } from 'react-router-dom'

import { InfrastructureManagementAppListType } from '@Common/Types'
import { CostBreakdownItemViewParamsType, CostBreakdownViewType } from '@PagesDevtron2.0/index'

const OVERVIEW = 'overview'

const APP_ENV_DETAIL_ROUTES = {
    OVERVIEW,
    APP_DETAILS: 'details',
    TRIGGER: 'trigger',
    CI_DETAILS: 'ci-details',
    CD_DETAILS: 'cd-details',
    CONFIGURATIONS: 'edit',
} as const

const RELEASE_TRACK_ADD_EDIT = 'track/:id'

export const BASE_ROUTES = {
    GETTING_STARTED: 'getting-started',
    LOGIN: {
        ROOT: 'login',
        SSO: 'sso',
        ADMIN: 'admin',
    },
    LICENSE_AUTH: 'license-auth',
    APPLICATION_MANAGEMENT: {
        ROOT: 'application-management',
        OVERVIEW,
        DEVTRON_APP: {
            ROOT: 'devtron-app',
            LIST: {
                ROOT: 'list',
                CREATE_APP: 'create-app',
            },
            DETAIL: {
                ROOT: ':appId',
                ...APP_ENV_DETAIL_ROUTES,
                DEPLOYMENT_METRICS: 'deployment-metrics',
            },
        },
        APPLICATION_GROUP: {
            ROOT: 'application-group',
            LIST: 'list',
            DETAIL: {
                ROOT: ':envId',
                ...APP_ENV_DETAIL_ROUTES,
            },
        },
        BULK_EDIT: 'bulk-edit',
        APPLICATION_TEMPLATES: {
            ROOT: 'templates/devtron-app',
            DETAIL: {
                ROOT: 'detail/:appId',
                OVERVIEW,
                CONFIGURATIONS: 'edit',
            },
            CREATE: 'create',
        },
        CONFIGURATIONS: {
            ROOT: 'configurations',
            GITOPS: 'gitops',
            GIT_ACCOUNTS: 'git-accounts',
            DEPLOYMENT_CHARTS: {
                ROOT: 'deployment-charts',
                EDIT: ':name/:resourceType',
            },
            NOTIFICATIONS: 'notifications',
            NOTIFICATIONS_ADD_NEW: 'notifications/new',
            SCOPED_VARIABLES: {
                ROOT: 'scoped-variables',
                CURRENT_VIEW: ':currentView?',
                ENVIRONMENT_DETAILS: 'environments/:environmentName',
            },
            BUILD_INFRA: {
                ROOT: 'build-infra',
                PROFILES: 'profiles',
                EDIT_PROFILE: 'profiles/edit/:profileName',
                APPLICATIONS: 'applications',
            },
        },
        POLICIES: {
            ROOT: 'policies',
            DEPLOYMENT_WINDOW: {
                ROOT: 'deployment-window',
                LIST: 'list',
                APPLY_TO: 'apply-to',
                CREATE: 'window/create',
                EDIT: 'window/edit',
            },
            APPROVAL_POLICY: {
                ROOT: 'approval-policy',
                POLICY: {
                    ROOT: 'policy',
                    CREATE: 'create',
                    EDIT: 'edit/:policyName',
                },
                APPLIED_POLICY: {
                    ROOT: 'applied-policy',
                    CREATE: 'create',
                    EDIT: 'edit/:appliedProfileId',
                },
                EXCEPTIONS: 'exceptions',
            },
            PLUGIN_POLICY: {
                ROOT: 'plugin-policy',
                PROFILES: {
                    ROOT: 'profiles',
                    OFFENDING_PIPELINES: 'offending-pipelines/:profileName',
                    CREATE: 'create',
                    EDIT: 'edit/:profileName',
                },
                APPLIED_PROFILES: {
                    ROOT: 'applied-profiles',
                    CREATE: 'create',
                    EDIT: 'edit/:appliedProfileId',
                },
            },
            PULL_IMAGE_DIGEST: 'pull-image-digest',
            TAG_POLICY: {
                ROOT: 'tag-policy',
                CREATE: 'create',
                EDIT: 'edit/:tagId',
            },
            FILTER_CONDITIONS: {
                ROOT: 'filter-conditions',
                ADD: 'add',
                EDIT: 'edit/:filterId',
            },
            IMAGE_PROMOTION: {
                ROOT: 'image-promotion',
                PROFILES: {
                    ROOT: 'profiles',
                    CREATE: 'create',
                    EDIT: 'edit/:profileName',
                },
                APPLIED_PROFILES: {
                    ROOT: 'applied-profiles',
                    CREATE: 'create',
                    EDIT: 'edit/:appliedProfileId',
                },
            },
            LOCK_DEPLOYMENT_CONFIGURATION: {
                ROOT: 'lock-deployment-configuration',
                PROFILES: {
                    ROOT: 'profiles',
                    CREATE: 'create',
                    EDIT: 'edit/:profileName',
                },
                APPLIED_PROFILES: {
                    ROOT: 'applied-profiles',
                    CREATE: 'create',
                    EDIT: 'edit/:appliedProfileId',
                },
            },
        },
    },
    INFRASTRUCTURE_MANAGEMENT: {
        ROOT: 'infrastructure-management',
        OVERVIEW,
        APPS: {
            ROOT: 'apps',
            LIST: ':appType',
            DEVTRON_CHART: 'dc/deployments/:appId/env/:envId',
            EXTERNAL_HELM_APP: 'ea/:appId/:appName',
            EXTERNAL_ARGO_APP: 'eaa/:clusterId/:appName/:namespace',
            EXTERNAL_FLUX_APP: 'external-flux/:clusterId/:appName/:namespace/:templateType',
        },
        CHART_STORE: {
            ROOT: 'chart-store/discover',
        },
        RESOURCE_BROWSER: {
            ROOT: 'resource-browser',
            CLUSTER_LIST: 'list',
            INSTALLATION_CLUSTER: 'installation-cluster/:installationId',
            COMPARE_CLUSTERS: 'compare-clusters',
            CLUSTER_DETAILS: {
                ROOT: ':clusterId',
                OVERVIEW,
                MONITORING_DASHBOARD: 'monitoring-dashboard',
                TERMINAL: 'terminal',
                CLUSTER_UPGRADE: 'cluster-upgrade',
                NODE_DETAIL: 'node/detail/:name',
                K8S_RESOURCE_DETAIL: ':namespace/:kind/:group/:name',
                K8S_RESOURCE_LIST: ':kind/:group',
                RESOURCE_RECOMMENDER: 'resource-recommender',
            },
        },
        RESOURCE_WATCHER: {
            ROOT: 'resource-watcher',
            WATCHERS: 'watchers',
            INTERCEPTED_CHANGES: 'intercepted-changes',
        },
    },
    SOFTWARE_RELEASE_MANAGEMENT: {
        ROOT: 'software-release-management',
        RELEASES: {
            ROOT: 'releases',
            CREATE: 'create',
            EDIT: 'edit/:releaseId',
            DETAIL: {
                ROOT: 'detail/:releaseTrack/:releaseVersion',
                OVERVIEW,
                REQUIREMENTS: {
                    ROOT: 'requirements/:appName?',
                    DEPLOYMENT_SOURCE: 'deployment-source',
                },
                ROLLOUT_RELEASE: 'rollout-release',
                HISTORY: 'rollout-history/:appId?/:envId?/:pipelineId?/:triggerId?',
                CONFIGURATIONS: 'configurations/:appId?/:envId?',
            },
            TRACK_ADD_EDIT: RELEASE_TRACK_ADD_EDIT,
            TRACK_DETAIL: 'track/detail/:trackName',
            CREATE_RELEASE_TRACK_ADD_EDIT: `create/${RELEASE_TRACK_ADD_EDIT}`,
            EDIT_RELEASE_TRACK_ADD_EDIT: `edit/:releaseId/${RELEASE_TRACK_ADD_EDIT}`,
        },
        TENANTS: {
            ROOT: 'tenants',
            CREATE: 'create',
            EDIT: 'edit/:tenantId',
            DETAIL: {
                ROOT: 'detail/:tenantId',
                OVERVIEW,
                INSTALLATIONS: 'installations/:installationId?',
                MAP_ENVIRONMENT: 'map-environment',
            },
        },
    },
    COST_VISIBILITY: {
        ROOT: 'cost-visibility',
        OVERVIEW,
        BREAKDOWN: {
            ROOT: 'breakdown/:breakdownViewType',
            DETAIL: `:${CostBreakdownItemViewParamsType.ITEM_NAME}/:${CostBreakdownItemViewParamsType.VIEW}/:${CostBreakdownItemViewParamsType.DETAIL}?`,
        },
        CONFIGURATIONS: 'configurations',
    },
    SECURITY_CENTER: {
        ROOT: 'security-center',
        OVERVIEW,
        VULNERABILITIES: {
            ROOT: 'vulnerabilities',
            DEPLOYMENTS: 'deployments',
            CVES: 'cves',
        },
        SECURITY_ENABLEMENT: 'security-enablement',
        POLICIES: 'policies',
    },
    AUTOMATION_AND_ENABLEMENT: {
        ROOT: 'automation-and-enablement',
        JOBS: {
            ROOT: 'job',
            LIST: {
                ROOT: 'list',
                CREATE_JOB: 'create-job',
            },
            DETAIL: {
                ROOT: ':appId',
                OVERVIEW: APP_ENV_DETAIL_ROUTES.OVERVIEW,
                TRIGGER: APP_ENV_DETAIL_ROUTES.TRIGGER,
                CI_DETAILS: APP_ENV_DETAIL_ROUTES.CI_DETAILS,
                CONFIGURATIONS: APP_ENV_DETAIL_ROUTES.CONFIGURATIONS,
            },
        },
    },
    DATA_PROTECTION_MANAGEMENT: {
        ROOT: 'data-protection-management',
        OVERVIEW,
        BACKUP_AND_SCHEDULE: {
            ROOT: 'backup-and-schedule/:view',
            DETAIL: 'detail/:id',
        },
        RESTORES: {
            ROOT: 'restores',
            DETAIL: ':restoreId',
        },
        BACKUP_LOCATIONS: {
            ROOT: 'backup-locations/:type',
            DETAIL: ':locationId',
        },
    },
    GLOBAL_CONFIG: {
        ROOT: 'global-configuration',
        HOST_URL: 'host-url',
        EXTERNAL_LINKS: 'external-links',
        CHART_REPOSITORIES: 'chart-repositories',
        CLUSTER_ENV: {
            ROOT: 'cluster-env',
            MANAGE_CATEGORIES: 'manage-categories',
        },
        DOCKER: 'docker',
        PROJECTS: 'projects',
        AUTH: {
            ROOT: 'auth',
            LOGIN_SERVICE: 'login-service',
            USERS: 'users',
            GROUPS: 'groups',
            API_TOKEN: 'api-token',
        },
    },
    STACK_MANAGER: {
        ROOT: 'stack-manager',
        DISCOVER_MODULES: 'discover',
        DISCOVER_MODULES_DETAILS: 'discover/details',
        INSTALLED_MODULES: 'installed',
        INSTALLED_MODULES_DETAILS: 'installed/details',
        ABOUT: 'about',
        ABOUT_RELEASES: 'about/releases',
    },
    NETWORK_STATUS_INTERFACE: {
        ROOT: 'network-status-interface',
        CREATE_CONTROLLER: 'controller/create',
        EDIT_CONTROLLER: 'controller/edit/:controllerId',
        CONTROLLER_DETAILS: 'controller/details/:controllerId',
        CUSTOMIZE_COLUMNS: 'customize-columns',
    },
} as const

const APPLICATION_MANAGEMENT_ROOT = `/${BASE_ROUTES.APPLICATION_MANAGEMENT.ROOT}` as const

const DEVTRON_APP_ROOT =
    `${APPLICATION_MANAGEMENT_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.ROOT}` as const
const DEVTRON_APP_DETAILS_ROOT =
    `${DEVTRON_APP_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.DETAIL.ROOT}` as const
const APP_GROUP_ROOT =
    `${APPLICATION_MANAGEMENT_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_GROUP.ROOT}` as const
const APP_GROUP_DETAIL_ROOT =
    `${APP_GROUP_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_GROUP.DETAIL.ROOT}` as const

const APP_TEMPLATES_ROOT =
    `${APPLICATION_MANAGEMENT_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_TEMPLATES.ROOT}` as const

const APPLICATION_MANAGEMENT_CONFIGURATIONS_ROOT =
    `${APPLICATION_MANAGEMENT_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.ROOT}` as const
const SCOPED_VARIABLES_ROOT =
    `${APPLICATION_MANAGEMENT_CONFIGURATIONS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.SCOPED_VARIABLES.ROOT}` as const
const BUILD_INFRA_ROOT =
    `${APPLICATION_MANAGEMENT_CONFIGURATIONS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.BUILD_INFRA.ROOT}` as const

const APPLICATION_MANAGEMENT_POLICIES_ROOT =
    `${APPLICATION_MANAGEMENT_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.ROOT}` as const

const DEPLOYMENT_WINDOW_ROOT =
    `${APPLICATION_MANAGEMENT_POLICIES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.DEPLOYMENT_WINDOW.ROOT}` as const

const APPROVAL_POLICY_ROOT =
    `${APPLICATION_MANAGEMENT_POLICIES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.APPROVAL_POLICY.ROOT}` as const
const APPROVAL_POLICY_POLICY =
    `${APPROVAL_POLICY_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.APPROVAL_POLICY.POLICY.ROOT}` as const
const APPROVAL_POLICY_APPLIED_POLICY =
    `${APPROVAL_POLICY_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.APPROVAL_POLICY.APPLIED_POLICY.ROOT}` as const

const PLUGIN_POLICY_ROOT =
    `${APPLICATION_MANAGEMENT_POLICIES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.PLUGIN_POLICY.ROOT}` as const
const PLUGIN_POLICY_PROFILES =
    `${PLUGIN_POLICY_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.PLUGIN_POLICY.PROFILES.ROOT}` as const
const PLUGIN_POLICY_APPLIED_PROFILES =
    `${PLUGIN_POLICY_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.PLUGIN_POLICY.APPLIED_PROFILES.ROOT}` as const

const IMAGE_PROMOTION_ROOT =
    `${APPLICATION_MANAGEMENT_POLICIES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.IMAGE_PROMOTION.ROOT}` as const
const IMAGE_PROMOTION_PROFILES =
    `${IMAGE_PROMOTION_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.IMAGE_PROMOTION.PROFILES.ROOT}` as const
const IMAGE_PROMOTION_APPLIED_PROFILES =
    `${IMAGE_PROMOTION_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.IMAGE_PROMOTION.APPLIED_PROFILES.ROOT}` as const

const TAG_POLICY_ROOT =
    `${APPLICATION_MANAGEMENT_POLICIES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.TAG_POLICY.ROOT}` as const

const FILTER_CONDITIONS_ROOT =
    `${APPLICATION_MANAGEMENT_POLICIES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.FILTER_CONDITIONS.ROOT}` as const

const LOCK_DEPLOYMENT_CONFIGURATION_ROOT =
    `${APPLICATION_MANAGEMENT_POLICIES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.LOCK_DEPLOYMENT_CONFIGURATION.ROOT}` as const
const LOCK_DEPLOYMENT_CONFIGURATION_PROFILES =
    `${LOCK_DEPLOYMENT_CONFIGURATION_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.LOCK_DEPLOYMENT_CONFIGURATION.PROFILES.ROOT}` as const
const LOCK_DEPLOYMENT_CONFIGURATION_APPLIED_PROFILES =
    `${LOCK_DEPLOYMENT_CONFIGURATION_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.LOCK_DEPLOYMENT_CONFIGURATION.APPLIED_PROFILES.ROOT}` as const

const INFRASTRUCTURE_MANAGEMENT_ROOT = `/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.ROOT}` as const
const INFRASTRUCTURE_MANAGEMENT_APPS_ROOT =
    `${INFRASTRUCTURE_MANAGEMENT_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.APPS.ROOT}` as const
const INFRASTRUCTURE_MANAGEMENT_APP_LIST =
    `${INFRASTRUCTURE_MANAGEMENT_APPS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.APPS.LIST}` as const
const RESOURCE_BROWSER_ROOT =
    `${INFRASTRUCTURE_MANAGEMENT_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.ROOT}` as const
const CLUSTER_DETAILS_ROOT =
    `${RESOURCE_BROWSER_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.CLUSTER_DETAILS.ROOT}` as const

const SOFTWARE_RELEASE_MANAGEMENT_ROOT = `/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.ROOT}` as const

const RELEASES_ROOT =
    `${SOFTWARE_RELEASE_MANAGEMENT_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.ROOT}` as const
const RELEASE_DETAIL_ROOT = `${RELEASES_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.DETAIL.ROOT}` as const

const TENANTS_ROOT =
    `${SOFTWARE_RELEASE_MANAGEMENT_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.TENANTS.ROOT}` as const
const TENANT_DETAIL_ROOT = `${TENANTS_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.TENANTS.DETAIL.ROOT}` as const

const COST_VISIBILITY_ROOT = `/${BASE_ROUTES.COST_VISIBILITY.ROOT}` as const
const COST_VISIBILITY_BREAKDOWN = `${COST_VISIBILITY_ROOT}/${BASE_ROUTES.COST_VISIBILITY.BREAKDOWN.ROOT}` as const

const SECURITY_CENTER_ROOT = `/${BASE_ROUTES.SECURITY_CENTER.ROOT}` as const

const JOBS_ROOT =
    `/${BASE_ROUTES.AUTOMATION_AND_ENABLEMENT.ROOT}/${BASE_ROUTES.AUTOMATION_AND_ENABLEMENT.JOBS.ROOT}` as const
const JOB_DETAIL_ROOT = `${JOBS_ROOT}/${BASE_ROUTES.AUTOMATION_AND_ENABLEMENT.JOBS.DETAIL.ROOT}` as const

const DATA_PROTECTION_MANAGEMENT_ROOT = `/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.ROOT}` as const
const GLOBAL_CONFIG_ROOT = `/${BASE_ROUTES.GLOBAL_CONFIG.ROOT}` as const
const GLOBAL_CONFIG_AUTH_ROOT = `${GLOBAL_CONFIG_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.AUTH.ROOT}` as const
const NETWORK_STATUS_INTERFACE_ROOT = `/${BASE_ROUTES.NETWORK_STATUS_INTERFACE.ROOT}` as const
const STACK_MANAGER_ROOT = `/${BASE_ROUTES.STACK_MANAGER.ROOT}` as const

export const ROUTER_URLS = {
    GETTING_STARTED: `/${BASE_ROUTES.GETTING_STARTED}`,
    LOGIN: {
        ROOT: `/${BASE_ROUTES.LOGIN.ROOT}`,
        SSO: `/${BASE_ROUTES.LOGIN.ROOT}/${BASE_ROUTES.LOGIN.SSO}`,
        ADMIN: `/${BASE_ROUTES.LOGIN.ROOT}/${BASE_ROUTES.LOGIN.ADMIN}`,
    },
    LICENSE_AUTH: `/${BASE_ROUTES.LICENSE_AUTH}`,
    // Application Management
    APPLICATION_MANAGEMENT_OVERVIEW: `${APPLICATION_MANAGEMENT_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.OVERVIEW}`,
    // -- Devtron App
    DEVTRON_APP: DEVTRON_APP_ROOT,
    DEVTRON_APP_LIST: `${DEVTRON_APP_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.LIST.ROOT}`,
    DEVTRON_APP_DETAILS: {
        ROOT: DEVTRON_APP_DETAILS_ROOT,
        OVERVIEW: `${DEVTRON_APP_DETAILS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.DETAIL.OVERVIEW}`,
        DETAILS: `${DEVTRON_APP_DETAILS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.DETAIL.APP_DETAILS}`,
        ENV_DETAILS: `${DEVTRON_APP_DETAILS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.DETAIL.APP_DETAILS}/:envId`,
        TRIGGER: `${DEVTRON_APP_DETAILS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.DETAIL.TRIGGER}`,
        CI_DETAILS: `${DEVTRON_APP_DETAILS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.DETAIL.CI_DETAILS}`,
        CD_DETAILS: `${DEVTRON_APP_DETAILS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.DETAIL.CD_DETAILS}`,
        DEPLOYMENT_METRICS: `${DEVTRON_APP_DETAILS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.DETAIL.DEPLOYMENT_METRICS}`,
        CONFIGURATIONS: `${DEVTRON_APP_DETAILS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.DETAIL.CONFIGURATIONS}`,
    },
    CREATE_DEVTRON_APP: `${DEVTRON_APP_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.LIST.ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.DEVTRON_APP.LIST.CREATE_APP}`,
    // -- Application Group
    APP_GROUP: APP_GROUP_ROOT,
    APP_GROUP_LIST: `${APP_GROUP_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_GROUP.LIST}`,
    APP_GROUP_DETAILS: {
        ROOT: APP_GROUP_DETAIL_ROOT,
        OVERVIEW: `${APP_GROUP_DETAIL_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_GROUP.DETAIL.OVERVIEW}`,
        DETAILS: `${APP_GROUP_DETAIL_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_GROUP.DETAIL.APP_DETAILS}`,
        APP_DETAILS: `${APP_GROUP_DETAIL_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_GROUP.DETAIL.APP_DETAILS}/:appId`,
        TRIGGER: `${APP_GROUP_DETAIL_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_GROUP.DETAIL.TRIGGER}`,
        CI_DETAILS: `${APP_GROUP_DETAIL_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_GROUP.DETAIL.CI_DETAILS}`,
        CD_DETAILS: `${APP_GROUP_DETAIL_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_GROUP.DETAIL.CD_DETAILS}`,
        CONFIGURATIONS: `${APP_GROUP_DETAIL_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_GROUP.DETAIL.CONFIGURATIONS}`,
    },
    BULK_EDIT: `${APPLICATION_MANAGEMENT_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.BULK_EDIT}`,
    APP_TEMPLATES: APP_TEMPLATES_ROOT,
    APP_TEMPLATE_CREATE: `${APP_TEMPLATES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_TEMPLATES.CREATE}`,
    APP_TEMPLATE_DETAIL: `${APP_TEMPLATES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.APPLICATION_TEMPLATES.DETAIL.ROOT}`,
    // -- Configurations
    APPLICATION_MANAGEMENT_CONFIGURATIONS: {
        ROOT: APPLICATION_MANAGEMENT_CONFIGURATIONS_ROOT,
        GITOPS: `${APPLICATION_MANAGEMENT_CONFIGURATIONS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.GITOPS}`,
        GIT_ACCOUNTS: `${APPLICATION_MANAGEMENT_CONFIGURATIONS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.GIT_ACCOUNTS}`,
        DEPLOYMENT_CHARTS: `${APPLICATION_MANAGEMENT_CONFIGURATIONS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.DEPLOYMENT_CHARTS.ROOT}`,
        NOTIFICATIONS: `${APPLICATION_MANAGEMENT_CONFIGURATIONS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.NOTIFICATIONS}`,
        SCOPED_VARIABLES: {
            ROOT: SCOPED_VARIABLES_ROOT,
            CURRENT_VIEW: `${SCOPED_VARIABLES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.SCOPED_VARIABLES.CURRENT_VIEW}`,
            ENVIRONMENT_DETAILS: `${SCOPED_VARIABLES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.SCOPED_VARIABLES.ENVIRONMENT_DETAILS}`,
        },
        BUILD_INFRA: {
            ROOT: BUILD_INFRA_ROOT,
            PROFILES: `${BUILD_INFRA_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.BUILD_INFRA.PROFILES}`,
            EDIT_PROFILE: `${BUILD_INFRA_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.BUILD_INFRA.EDIT_PROFILE}`,
            APPLICATIONS: `${BUILD_INFRA_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.CONFIGURATIONS.BUILD_INFRA.APPLICATIONS}`,
        },
    },
    // -- Policies
    APPLICATION_MANAGEMENT_POLICIES: {
        ROOT: APPLICATION_MANAGEMENT_POLICIES_ROOT,
        DEPLOYMENT_WINDOW: {
            ROOT: DEPLOYMENT_WINDOW_ROOT,
            LIST: `${DEPLOYMENT_WINDOW_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.DEPLOYMENT_WINDOW.LIST}`,
            CREATE: `${DEPLOYMENT_WINDOW_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.DEPLOYMENT_WINDOW.CREATE}`,
        },
        APPROVAL_POLICY: {
            ROOT: APPROVAL_POLICY_ROOT,
            POLICY: {
                ROOT: APPROVAL_POLICY_POLICY,
                CREATE: `${APPROVAL_POLICY_POLICY}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.APPROVAL_POLICY.POLICY.CREATE}`,
                EDIT: `${APPROVAL_POLICY_POLICY}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.APPROVAL_POLICY.POLICY.EDIT}`,
            },
            APPLIED_POLICY: {
                ROOT: APPROVAL_POLICY_APPLIED_POLICY,
                CREATE: `${APPROVAL_POLICY_APPLIED_POLICY}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.APPROVAL_POLICY.APPLIED_POLICY.CREATE}`,
                EDIT: `${APPROVAL_POLICY_APPLIED_POLICY}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.APPROVAL_POLICY.APPLIED_POLICY.EDIT}`,
            },
            EXCEPTIONS: `${APPROVAL_POLICY_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.APPROVAL_POLICY.EXCEPTIONS}`,
        },
        PLUGIN_POLICY: {
            ROOT: PLUGIN_POLICY_ROOT,
            PROFILES: {
                ROOT: PLUGIN_POLICY_PROFILES,
                OFFENDING_PIPELINES: `${PLUGIN_POLICY_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.PLUGIN_POLICY.PROFILES.OFFENDING_PIPELINES}`,
                CREATE: `${PLUGIN_POLICY_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.PLUGIN_POLICY.PROFILES.CREATE}`,
                EDIT: `${PLUGIN_POLICY_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.PLUGIN_POLICY.PROFILES.EDIT}`,
            },
            APPLIED_PROFILES: {
                ROOT: PLUGIN_POLICY_APPLIED_PROFILES,
                CREATE: `${PLUGIN_POLICY_APPLIED_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.PLUGIN_POLICY.APPLIED_PROFILES.CREATE}`,
                EDIT: `${PLUGIN_POLICY_APPLIED_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.PLUGIN_POLICY.APPLIED_PROFILES.EDIT}`,
            },
        },
        PULL_IMAGE_DIGEST: `${APPLICATION_MANAGEMENT_POLICIES_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.PULL_IMAGE_DIGEST}`,
        TAG_POLICY: {
            ROOT: TAG_POLICY_ROOT,
            CREATE: `${TAG_POLICY_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.TAG_POLICY.CREATE}`,
            EDIT: `${TAG_POLICY_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.TAG_POLICY.EDIT}`,
        },
        FILTER_CONDITIONS: {
            ROOT: FILTER_CONDITIONS_ROOT,
            ADD: `${FILTER_CONDITIONS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.FILTER_CONDITIONS.ADD}`,
            EDIT: `${FILTER_CONDITIONS_ROOT}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.FILTER_CONDITIONS.EDIT}`,
        },
        IMAGE_PROMOTION: {
            ROOT: IMAGE_PROMOTION_ROOT,
            PROFILES: {
                ROOT: IMAGE_PROMOTION_PROFILES,
                CREATE: `${IMAGE_PROMOTION_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.IMAGE_PROMOTION.PROFILES.CREATE}`,
                EDIT: `${IMAGE_PROMOTION_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.IMAGE_PROMOTION.PROFILES.EDIT}`,
            },
            APPLIED_PROFILES: {
                ROOT: IMAGE_PROMOTION_APPLIED_PROFILES,
                CREATE: `${IMAGE_PROMOTION_APPLIED_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.IMAGE_PROMOTION.APPLIED_PROFILES.CREATE}`,
                EDIT: `${IMAGE_PROMOTION_APPLIED_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.IMAGE_PROMOTION.APPLIED_PROFILES.EDIT}`,
            },
        },
        LOCK_DEPLOYMENT_CONFIGURATION: {
            ROOT: LOCK_DEPLOYMENT_CONFIGURATION_ROOT,
            PROFILES: {
                ROOT: LOCK_DEPLOYMENT_CONFIGURATION_PROFILES,
                CREATE: `${LOCK_DEPLOYMENT_CONFIGURATION_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.LOCK_DEPLOYMENT_CONFIGURATION.PROFILES.CREATE}`,
                EDIT: `${LOCK_DEPLOYMENT_CONFIGURATION_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.LOCK_DEPLOYMENT_CONFIGURATION.PROFILES.EDIT}`,
            },
            APPLIED_PROFILES: {
                ROOT: LOCK_DEPLOYMENT_CONFIGURATION_APPLIED_PROFILES,
                CREATE: `${LOCK_DEPLOYMENT_CONFIGURATION_APPLIED_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.LOCK_DEPLOYMENT_CONFIGURATION.APPLIED_PROFILES.CREATE}`,
                EDIT: `${LOCK_DEPLOYMENT_CONFIGURATION_APPLIED_PROFILES}/${BASE_ROUTES.APPLICATION_MANAGEMENT.POLICIES.LOCK_DEPLOYMENT_CONFIGURATION.APPLIED_PROFILES.EDIT}`,
            },
        },
    },

    // Infrastructure Management
    INFRASTRUCTURE_MANAGEMENT_OVERVIEW: `${INFRASTRUCTURE_MANAGEMENT_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.OVERVIEW}`,
    INFRASTRUCTURE_MANAGEMENT_APPS: INFRASTRUCTURE_MANAGEMENT_APPS_ROOT,
    INFRASTRUCTURE_MANAGEMENT_APP_LIST: {
        ROUTE: INFRASTRUCTURE_MANAGEMENT_APP_LIST,
        HELM: generatePath(INFRASTRUCTURE_MANAGEMENT_APP_LIST, { appType: InfrastructureManagementAppListType.HELM }),
        ARGO_CD: generatePath(INFRASTRUCTURE_MANAGEMENT_APP_LIST, {
            appType: InfrastructureManagementAppListType.ARGO_CD,
        }),
        FLUX_CD: generatePath(INFRASTRUCTURE_MANAGEMENT_APP_LIST, {
            appType: InfrastructureManagementAppListType.FLUX_CD,
        }),
    },
    INFRASTRUCTURE_MANAGEMENT_APP_DETAIL: {
        DEVTRON_CHART: `${INFRASTRUCTURE_MANAGEMENT_APPS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.APPS.DEVTRON_CHART}`,
        EXTERNAL_HELM_APP: `${INFRASTRUCTURE_MANAGEMENT_APPS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.APPS.EXTERNAL_HELM_APP}`,
        EXTERNAL_ARGO_APP: `${INFRASTRUCTURE_MANAGEMENT_APPS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.APPS.EXTERNAL_ARGO_APP}`,
        EXTERNAL_FLUX_APP: `${INFRASTRUCTURE_MANAGEMENT_APPS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.APPS.EXTERNAL_FLUX_APP}`,
    },
    CHART_STORE: `${INFRASTRUCTURE_MANAGEMENT_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.CHART_STORE.ROOT}`,
    RESOURCE_BROWSER: {
        ROOT: RESOURCE_BROWSER_ROOT,
        CLUSTER_LIST: `${RESOURCE_BROWSER_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.CLUSTER_LIST}`,
        INSTALLATION_CLUSTER: `${RESOURCE_BROWSER_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.INSTALLATION_CLUSTER}`,
        COMPARE_CLUSTERS: `${RESOURCE_BROWSER_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.COMPARE_CLUSTERS}`,
        CLUSTER_DETAILS: {
            ROOT: CLUSTER_DETAILS_ROOT,
            OVERVIEW: `${CLUSTER_DETAILS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.CLUSTER_DETAILS.OVERVIEW}`,
            MONITORING_DASHBOARD: `${CLUSTER_DETAILS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.CLUSTER_DETAILS.MONITORING_DASHBOARD}`,
            TERMINAL: `${CLUSTER_DETAILS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.CLUSTER_DETAILS.TERMINAL}`,
            CLUSTER_UPGRADE: `${CLUSTER_DETAILS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.CLUSTER_DETAILS.CLUSTER_UPGRADE}`,
            NODE_DETAIL: `${CLUSTER_DETAILS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.CLUSTER_DETAILS.NODE_DETAIL}`,
            K8S_RESOURCE_DETAIL: `${CLUSTER_DETAILS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.CLUSTER_DETAILS.K8S_RESOURCE_DETAIL}`,
            K8S_RESOURCE_LIST: `${CLUSTER_DETAILS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.CLUSTER_DETAILS.K8S_RESOURCE_LIST}`,
            RESOURCE_RECOMMENDER: `${CLUSTER_DETAILS_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_BROWSER.CLUSTER_DETAILS.RESOURCE_RECOMMENDER}`,
        },
    },
    RESOURCE_WATCHER: `${INFRASTRUCTURE_MANAGEMENT_ROOT}/${BASE_ROUTES.INFRASTRUCTURE_MANAGEMENT.RESOURCE_WATCHER.ROOT}`,

    // Software Release Management
    RELEASES: {
        ROOT: RELEASES_ROOT,
        CREATE: `${RELEASES_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.CREATE}`,
        EDIT: `${RELEASES_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.EDIT}`,
        DETAIL: {
            ROOT: RELEASE_DETAIL_ROOT,
            OVERVIEW: `${RELEASE_DETAIL_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.DETAIL.OVERVIEW}`,
            REQUIREMENTS: `${RELEASE_DETAIL_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.DETAIL.REQUIREMENTS.ROOT}`,
            REQUIREMENTS_DEPLOYMENT_SOURCE: `${RELEASE_DETAIL_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.DETAIL.REQUIREMENTS.ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.DETAIL.REQUIREMENTS.DEPLOYMENT_SOURCE}`,
            ROLLOUT_RELEASE: `${RELEASE_DETAIL_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.DETAIL.ROLLOUT_RELEASE}`,
            HISTORY: `${RELEASE_DETAIL_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.DETAIL.HISTORY}`,
            CONFIGURATIONS: `${RELEASE_DETAIL_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.DETAIL.CONFIGURATIONS}`,
        },
        TRACK_ADD_EDIT: `${RELEASES_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.TRACK_ADD_EDIT}`,
        CREATE_RELEASE_TRACK_ADD_EDIT: `${RELEASES_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.CREATE_RELEASE_TRACK_ADD_EDIT}`,
        EDIT_RELEASE_TRACK_ADD_EDIT: `${RELEASES_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.EDIT_RELEASE_TRACK_ADD_EDIT}`,
        TRACK_DETAIL: `${RELEASES_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.RELEASES.TRACK_DETAIL}`,
    },
    TENANTS: {
        ROOT: TENANTS_ROOT,
        CREATE: `${TENANTS_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.TENANTS.CREATE}`,
        EDIT: `${TENANTS_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.TENANTS.EDIT}`,
        DETAIL: {
            ROOT: TENANT_DETAIL_ROOT,
            OVERVIEW: `${TENANT_DETAIL_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.TENANTS.DETAIL.OVERVIEW}`,
            INSTALLATIONS: `${TENANT_DETAIL_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.TENANTS.DETAIL.INSTALLATIONS}`,
            MAP_ENVIRONMENT: `${TENANT_DETAIL_ROOT}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.TENANTS.DETAIL.INSTALLATIONS}/${BASE_ROUTES.SOFTWARE_RELEASE_MANAGEMENT.TENANTS.DETAIL.MAP_ENVIRONMENT}`,
        },
    },

    // Cost Visibility
    COST_VISIBILITY_OVERVIEW: `${COST_VISIBILITY_ROOT}/${BASE_ROUTES.COST_VISIBILITY.OVERVIEW}`,
    COST_VISIBILITY_BREAKDOWN: {
        ROUTE: COST_VISIBILITY_BREAKDOWN,
        CLUSTERS: generatePath(COST_VISIBILITY_BREAKDOWN, {
            breakdownViewType: CostBreakdownViewType.CLUSTERS,
        }),
        ENVIRONMENTS: generatePath(COST_VISIBILITY_BREAKDOWN, {
            breakdownViewType: CostBreakdownViewType.ENVIRONMENTS,
        }),
        APPLICATIONS: generatePath(COST_VISIBILITY_BREAKDOWN, {
            breakdownViewType: CostBreakdownViewType.APPLICATIONS,
        }),
        PROJECTS: generatePath(COST_VISIBILITY_BREAKDOWN, {
            breakdownViewType: CostBreakdownViewType.PROJECTS,
        }),
    },
    COST_VISIBILITY_BREAKDOWN_DETAIL: `${COST_VISIBILITY_BREAKDOWN}/${BASE_ROUTES.COST_VISIBILITY.BREAKDOWN.DETAIL}`,
    COST_VISIBILITY_CONFIGURATIONS: `${COST_VISIBILITY_ROOT}/${BASE_ROUTES.COST_VISIBILITY.CONFIGURATIONS}`,

    // Security Center
    SECURITY_CENTER_OVERVIEW: `${SECURITY_CENTER_ROOT}/${BASE_ROUTES.SECURITY_CENTER.OVERVIEW}`,
    SECURITY_CENTER_VULNERABILITIES: `${SECURITY_CENTER_ROOT}/${BASE_ROUTES.SECURITY_CENTER.VULNERABILITIES.ROOT}`,
    SECURITY_CENTER_VULNERABILITY_DEPLOYMENTS: `${SECURITY_CENTER_ROOT}/${BASE_ROUTES.SECURITY_CENTER.VULNERABILITIES.ROOT}/${BASE_ROUTES.SECURITY_CENTER.VULNERABILITIES.DEPLOYMENTS}`,
    SECURITY_CENTER_VULNERABILITY_CVES: `${SECURITY_CENTER_ROOT}/${BASE_ROUTES.SECURITY_CENTER.VULNERABILITIES.ROOT}/${BASE_ROUTES.SECURITY_CENTER.VULNERABILITIES.CVES}`,
    SECURITY_CENTER_SECURITY_ENABLEMENT: `${SECURITY_CENTER_ROOT}/${BASE_ROUTES.SECURITY_CENTER.SECURITY_ENABLEMENT}`,
    SECURITY_CENTER_POLICIES: `${SECURITY_CENTER_ROOT}/${BASE_ROUTES.SECURITY_CENTER.POLICIES}`,

    // Automation and Enablement
    JOBS: JOBS_ROOT,
    JOBS_LIST: `${JOBS_ROOT}/${BASE_ROUTES.AUTOMATION_AND_ENABLEMENT.JOBS.LIST.ROOT}`,
    CREATE_JOB: `${JOBS_ROOT}/${BASE_ROUTES.AUTOMATION_AND_ENABLEMENT.JOBS.LIST.ROOT}/${BASE_ROUTES.AUTOMATION_AND_ENABLEMENT.JOBS.LIST.CREATE_JOB}`,
    JOB_DETAIL: {
        ROOT: JOB_DETAIL_ROOT,
        OVERVIEW: `${JOB_DETAIL_ROOT}/${BASE_ROUTES.AUTOMATION_AND_ENABLEMENT.JOBS.DETAIL.OVERVIEW}`,
        TRIGGER: `${JOB_DETAIL_ROOT}/${BASE_ROUTES.AUTOMATION_AND_ENABLEMENT.JOBS.DETAIL.TRIGGER}`,
        CI_DETAILS: `${JOB_DETAIL_ROOT}/${BASE_ROUTES.AUTOMATION_AND_ENABLEMENT.JOBS.DETAIL.CI_DETAILS}`,
        CONFIGURATIONS: `${JOB_DETAIL_ROOT}/${BASE_ROUTES.AUTOMATION_AND_ENABLEMENT.JOBS.DETAIL.CONFIGURATIONS}`,
    },

    // Data Protection Management
    DATA_PROTECTION_MANAGEMENT_OVERVIEW: `${DATA_PROTECTION_MANAGEMENT_ROOT}/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.OVERVIEW}`,
    DATA_PROTECTION_MANAGEMENT_BACKUP_AND_SCHEDULE: `${DATA_PROTECTION_MANAGEMENT_ROOT}/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.BACKUP_AND_SCHEDULE.ROOT}`,
    DATA_PROTECTION_MANAGEMENT_BACKUP_AND_SCHEDULE_DETAIL: `${DATA_PROTECTION_MANAGEMENT_ROOT}/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.BACKUP_AND_SCHEDULE.ROOT}/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.BACKUP_AND_SCHEDULE.DETAIL}`,
    DATA_PROTECTION_MANAGEMENT_RESTORES: `${DATA_PROTECTION_MANAGEMENT_ROOT}/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.RESTORES.ROOT}`,
    DATA_PROTECTION_MANAGEMENT_RESTORES_DETAIL: `${DATA_PROTECTION_MANAGEMENT_ROOT}/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.RESTORES.ROOT}/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.RESTORES.DETAIL}`,
    DATA_PROTECTION_MANAGEMENT_BACKUP_LOCATIONS: `${DATA_PROTECTION_MANAGEMENT_ROOT}/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.BACKUP_LOCATIONS.ROOT}`,
    DATA_PROTECTION_MANAGEMENT_BACKUP_LOCATIONS_DETAIL: `${DATA_PROTECTION_MANAGEMENT_ROOT}/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.BACKUP_LOCATIONS.ROOT}/${BASE_ROUTES.DATA_PROTECTION_MANAGEMENT.BACKUP_LOCATIONS.DETAIL}`,

    // Global Config
    GLOBAL_CONFIG_HOST_URL: `${GLOBAL_CONFIG_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.HOST_URL}`,
    GLOBAL_CONFIG_EXTERNAL_LINKS: `${GLOBAL_CONFIG_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.EXTERNAL_LINKS}`,
    GLOBAL_CONFIG_CHART_REPOSITORIES: `${GLOBAL_CONFIG_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.CHART_REPOSITORIES}`,
    GLOBAL_CONFIG_CLUSTER_ENV: `${GLOBAL_CONFIG_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.CLUSTER_ENV.ROOT}`,
    GLOBAL_CONFIG_DOCKER: `${GLOBAL_CONFIG_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.DOCKER}`,
    GLOBAL_CONFIG_PROJECTS: `${GLOBAL_CONFIG_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.PROJECTS}`,
    GLOBAL_CONFIG_AUTH: {
        LOGIN_SERVICE: `${GLOBAL_CONFIG_AUTH_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.AUTH.LOGIN_SERVICE}`,
        USERS: `${GLOBAL_CONFIG_AUTH_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.AUTH.USERS}`,
        GROUPS: `${GLOBAL_CONFIG_AUTH_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.AUTH.GROUPS}`,
        API_TOKEN: `${GLOBAL_CONFIG_AUTH_ROOT}/${BASE_ROUTES.GLOBAL_CONFIG.AUTH.API_TOKEN}`,
    },

    // Network Status Interface
    NETWORK_STATUS_INTERFACE: {
        ROOT: NETWORK_STATUS_INTERFACE_ROOT,
        CREATE_CONTROLLER: `${NETWORK_STATUS_INTERFACE_ROOT}/${BASE_ROUTES.NETWORK_STATUS_INTERFACE.CREATE_CONTROLLER}`,
        EDIT_CONTROLLER: `${NETWORK_STATUS_INTERFACE_ROOT}/${BASE_ROUTES.NETWORK_STATUS_INTERFACE.EDIT_CONTROLLER}`,
        CONTROLLER_DETAILS: `${NETWORK_STATUS_INTERFACE_ROOT}/${BASE_ROUTES.NETWORK_STATUS_INTERFACE.CONTROLLER_DETAILS}`,
        CUSTOMIZE_COLUMNS: `${NETWORK_STATUS_INTERFACE_ROOT}/${BASE_ROUTES.NETWORK_STATUS_INTERFACE.CUSTOMIZE_COLUMNS}`,
    },

    STACK_MANAGER: {
        ROOT: STACK_MANAGER_ROOT,
        DISCOVER_MODULES: `${STACK_MANAGER_ROOT}/${BASE_ROUTES.STACK_MANAGER.DISCOVER_MODULES}`,
        DISCOVER_MODULES_DETAILS: `${STACK_MANAGER_ROOT}/${BASE_ROUTES.STACK_MANAGER.DISCOVER_MODULES_DETAILS}`,
        INSTALLED_MODULES: `${STACK_MANAGER_ROOT}/${BASE_ROUTES.STACK_MANAGER.INSTALLED_MODULES}`,
        INSTALLED_MODULES_DETAILS: `${STACK_MANAGER_ROOT}/${BASE_ROUTES.STACK_MANAGER.INSTALLED_MODULES_DETAILS}`,
        ABOUT: `${STACK_MANAGER_ROOT}/${BASE_ROUTES.STACK_MANAGER.ABOUT}`,
        ABOUT_RELEASES: `${STACK_MANAGER_ROOT}/${BASE_ROUTES.STACK_MANAGER.ABOUT_RELEASES}`,
    },
} as const
